lua/venv-selector/init.lua, lua/venv-selector/utils.lua
Hello!,
Firstable thank you for all your work in this good plugin. I tryed to use it in my windows laptop and discover that the construction path for python executable not work and the split by final slash only works on Linux and Mac too.
For this reason I created this pull request with one solution for this problems.
The another big change was the creation of one separate function that do all the work of set environment vars and change the python that use Pyright. I do this change for create a function that I can call like a functional api when I try to restore a session that has with the path of the virtualenv and not need to call to command and select with Telescope the path.
The rest of the changes was dided by the Lua's formatter. If you preferred I try to deactivate it and recreate …
=> Api Method and fix windows paths

lua/venv-selector/venv.lua
Instead of using `print()` changed to use `vim.notify()` for better user experience.
=> feat: use vim.notify to update activated venv

lua/venv-selector/system.lua
since this last update with the caching i can't start venvs because i get this error:
the path for mac should be `/Users/<username>/` instead of `/home/<username>/`.
i tried to do it with `~/.cache` which will look nicer and work for both mac and linux, but i got errors from,`writefile` function.
so i just put the full path for mac.
maybe adding an option to not cache at all is a great option if paths are not standard and i just dont want to get these errors?
even if not loading from cache, it still tries to write the cache which can cause bugs.
=> fix cache paths for macOS

README.md, lua/venv-selector/config.lua, lua/venv-selector/system.lua, lua/venv-selector/venv.lua
Hello folks!
From the discussion on #18 I decided to try to start the implementation (Thanks @linux-cultist for setting the path).
There are a few things missing:
~~I also wanted to add a way to disable some managers to avoid noise and decided to go with disabling it using an empty string `""`, not sure there's a better way in Lua (I'm fairly new to the language).~~ **(Removed as per suggestion)**
Last but not least, I'm really sorry about the indentation mess. My editor uses 2 spaces as default and I was trying to fix it manually but it got messy :rofl: 
I'd love to know how/what to configure in order to comply with the style (=
closes #18
=> feat: Add pyenv-virtualenv support

lua/venv-selector/venv.lua
=> Don't display error if cached venv was not found

lua/venv-selector/system.lua
From the issue: https://github.com/linux-cultist/venv-selector.nvim/issues/28#issue-1748343756
When select a venv on Windows，you get an error:
```
E5108: Error executing lua Vim:E482: Can't open file %APPDATA%\venv-selector\venvs.json for writing: no such file or directory
stack traceback:
[C]: in function 'writefile'
...-data/lazy/venv-selector.nvim/lua/venv-selector/venv.lua:303: in function 'cache_venv'
...-data/lazy/venv-selector.nvim/lua/venv-selector/venv.lua:207: in function 'activate_venv'
.../lazy/venv-selector.nvim/lua/venv-selector/telescope.lua:76: in function 'key_func'
...nvim-data/lazy/telescope.nvim/lua/telescope/mappings.lua:352: in function 'execute_keymap'
[string ":lua"]:1: in main chunk
Press ENTER or type command to continue```
```
=> Fix: Can't open file %APPDATA%\venv-selector\venvs.json for writing

lua/venv-selector/system.lua
@linux-cultist I have been unable to load it locally with `lazynvim`, so I can't tell if it works 😅
Any pointers?
=> Fix Hatch path on Darwin

lua/venv-selector/init.lua, lua/venv-selector/mytelescope.lua, lua/venv-selector/venv.lua
#46 
Summary of changes:
- `mytelescope.show_results` only refresh telescope now, the part of code of show new picker now move to `mytelescope.open`.
- `venv.reload` rename to `venv.load`. And, move some condition to `mytelescope.open`.
- delay by 10ms when refresh to achieve a visual refresh effect.
<details> 
<summary>Before</summary>
https://github.com/linux-cultist/venv-selector.nvim/assets/32055974/adfe1c7c-c6e8-491f-b082-026ada93bb01
</details>
<details> 
<summary>After</summary>
https://github.com/linux-cultist/venv-selector.nvim/assets/32055974/2574bb79-dbf9-4713-9f25-8d71c7a5c05d
</details>
=> Another way to refresh telescope

lua/venv-selector/mytelescope.lua, lua/venv-selector/venv.lua
When venv-selector is loaded, telescope is also loaded. Even though I didn't set the telescope as a dependency in the lazy spec, and didn't use "VenvSelect" yet. I think It is common practice to set telescope.nvim to lazy load.
So, I moved all the "requires telescope" statements into functions so that telescope.nvim can be loaded when it is actually needed.
Also, I think top-to-bottom search result is better if the input box is at the top.
=> Lazy load telescope viewer

lua/venv-selector/system.lua, lua/venv-selector/venv.lua
Windows uses `;` to separate entries in the `PATH` environment variable. This was hardcoded to `:` which meant that a terminal in nvim wouldn't find the venv's `Scripts` directory.
Also fixes a small typo in `sys.get_info()`.
=> Fix Windows $PATH entry separator character

README.md, lua/venv-selector/config.lua, lua/venv-selector/system.lua, lua/venv-selector/venv.lua
It's well known that there is a whole mess of python dependency managers, of which most are handled by this plugin. However, [PDM](https://pdm.fming.dev/) as a more popular alternative to hatch is missing. This PR should do the trick, however, PDM defaults to "normal" `.venv` directories.  The location given here should be the location of venvs in case of a configuration `venv.in_project = false` for PDM.
=> Add PDM as a python dependency manager

README.md
The Lua table formatting in the Lazy configuration examples is wrong. This PR corrects the examples.
=> Fix syntax error in keymap examples for configuration via Lazy

README.md
A few more pretty pedantic updates to the README.
The example key binding commands starts with `<cmd>:` which is a pleonasm since `cmd` is a synonym for `:` :-)
This PR removes the `:` and also fixes an overlooked over-indentation from my last PR.
=> Remove superfluous colons in key binding examples

lua/venv-selector/hooks.lua
The current pyright hook resets all settings passed in to lspconfig except for the `settings` value. This is documented in #58. 
This PR essentially reverts commit `a37ea94`. The main difference is that all active pyright clients are updated instead of the first one. This snippet is heavily inspired by https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/pyright.lua.
=> Replace pyright hook

README.md, lua/venv-selector/config.lua, lua/venv-selector/hooks.lua, lua/venv-selector/init.lua, lua/venv-selector/venv.lua
This PR does a few general purpose cleanups:
1. Updates `vim.lsp.get_active_clients` to `vim.lsp.get_clients` if it's available since this function is getting deprecated in the upcoming v0.10 release. This simply provides some future proofing when that original function gets removed
2. Adds an `execute_for_clients` call that executes the callback for all clients rather than just the first one like `execute_for_client`. This is very useful for creating hooks like the `pyright` one
3. Adds back in the `pylance` hook just in case anyone uses it for any reason
4. Formats the Lua code in the README to follow the provided `stylua` configuration.
=> General hook cleanup

lua/venv-selector/venv.lua
This PR fixes a bug for Windows users with conda environments.
The plugin originally sets the environment variable `$VIRTUAL_ENV` when activating virtual environments. This variable is used by `nvim-dap-python` to set the Python interpreter path for debugging. However, the relative path of python interpreter for Windows conda environments is `[venv]\python.exe`, which is different from other types virtual environments, whose relative path is `[venv]\Scripts\python.exe`. Thus setting `$VIRTUAL_ENV` leads to a wrong python path (namely `[venv]\Scripts\python.exe`) for `nvim-dap-python`. This can also be seen from the code of `nvim-dap-python` plugin:
```
local get_python_path = function()
local venv_path = os.getenv('VIRTUAL_ENV')
if venv_path then
if is_windows() then
return venv_path .. …
```
=> Set $CONDA_PREFIX instead of $VIRTUAL_ENV for conda environments

lua/venv-selector/system.lua
The default PDM venv location was chosen according to the pdm documentation but does not match the default configuration on my (Arch linux) machine. This PR fixes that.
=> Fix default pdm location

lua/venv-selector/venv.lua
Otherwise `VIRTUAL_ENV` is never set on linux
=> Fix win32 guard when activating venvs

lua/venv-selector/hooks.lua
Summary of changes:
1. Simplify pylsp hook and use `workspace/didChangeConfiguration` instead of the `setup` function in pylsp hook.
2. pyright and pylance hook no longer work on neovim nightly due to https://github.com/neovim/neovim/commit/9f8c96240dc0318bd92a646966917e8fe0641144. (`client.config.settings` is readonly on neovim nightly)
3. `execut_for_clients` and `execute_for_client` do the same thing.
`vim.lsp.get_active_clients({name="name"})` always return one client, even thought it attaches onto many buffer. So, there is no need to use `vim.tbl_map`.
=> Enhance hooks and ensure compatibility with nightly build

lua/venv-selector/workspace.lua
`log` doesn't exist in the global namespace, so we get a `attempt to index global 'log' (a nil value)` error. Add a reference to the logger module to avoid this
=> Fix log call

lua/venv-selector/config.lua
The current defaults only search for the Python binary in non-hidden directories when searching in the current working directory. It ignores the folders like '.venv' and '.env', commonly used patterns to name a virtual environment when created using the command `python3 -m venv .venv`.
=> Also search for hidden folders in the current directory on default

lua/venv-selector/init.lua
This fixes the init check so that `stay_on_this_version = true` really removes the startup prompt.
=> fix: stay_on_this_version check

lua/venv-selector/gui.lua
Fixes [#144](https://github.com/linux-cultist/venv-selector.nvim/issues/144).
Just a small fix for people who use telescope's normal mode.
=> fix: select venv instead of open bin/python file by <cr> in normal mode

README.md, lua/venv-selector/cached_venv.lua, lua/venv-selector/gui.lua, lua/venv-selector/init.lua, lua/venv-selector/venv.lua
Hi there,
First of all, thank you for this great plugin, I use it daily. 
I was trying to integrate this plugin with session switching via possession.nvim, and had the need to be able to manually activate virtual environments. Unfortunately, the `regexp` version does not expose an activate function, and the internal functions don't have a convenient interface for external use.
I made an attempt to slightly refactor the `venv` module to create a single `activate` function which does all the tasks one would expect. With this refactor, we can easily expose `M.activate(path, type)`. I have tried to keep the logic nearly identical during the refactor, but there are some slight changes, which I'll highlight in the comments.
Let me know if this is something you'd be willing to merge.
=> feat: expose activate function

lua/venv-selector/cached_venv.lua
Fall back to default cache file if user cash file has not been loaded in yet.
=> cached_venv.lua: fix for cache_file

README.md, lua/venv-selector/cached_venv.lua, lua/venv-selector/config.lua, lua/venv-selector/health.lua, lua/venv-selector/hooks.lua, lua/venv-selector/init.lua, lua/venv-selector/search.lua
Hello 👋🏼 
First, thanks for this plugin!
I allowed myself to submit this PR adding multiple improvements to the settings handling:
- remove the unnecessary `settings` level (in a backward-compatible way)
- add a Neovim health check for it
- simplify the associated documentation (same indent, format... for all example, add syntax highlighting)
- follow `lazy.vim` recommendations in examples ([`opts` over `config`](https://lazy.folke.io/spec#spec-setup))
- add some [LuaCATS annotations](https://luals.github.io/wiki/annotations/), so users can benefit from completion and documentation from Lua LSP
Here's the health check for settings:
You can see the rendered README [here](https://github.com/noirbizarre/venv-selector.nvim/tree/unwrap-settings#readme)
=> Improve settings management

lua/venv-selector/config.lua
Newer versions of virtualenv add a .gitignore file containing a line with * in it, which ignores all files under the virtualenv. If the virtualenv happens to be under a git repository (such as when a user's home directory is tracked by git), fd will respect the gitignore files it sees in virtualenvs, causing venv-selector's default searches to fail to work as intended.
=> Use --no-ignore-vcs in default searches

lua/venv-selector/venv.lua
**Fix conda environment path resolution on Windows**
On Linux, the conda environment’s Python executable is located at:
```
<conda_env_path>/<conda_env_name>/bin/python
```
Whereas on Windows it is located at:
```
<conda_env_path>\<conda_env_name>\python.exe
```
This means that to correctly resolve the conda base path (starting from the executable), `get_base` needs to be called twice on Linux, but only once on Windows.
Without this adjustment, environments were not being activated properly. In my case, this caused `nvim-dap-python` to work as expected on Linux but fail on Windows.
This PR makes the necessary changes to fix the issue.
=> Fix conda environment path resolution on Windows
